# 3.3 다차원 배열의 계산

## 3.3.1 다차원 배열

In [2]:
import numpy as np
A = np.array([1,2,3,4])
print(A)
print(np.ndim(A))
print(A.shape)
print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [4]:
B = np.array([[1,2],[3,4],[5,6]])
print(B)
print(np.ndim(B)) # 차원의 크기
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


## 3.3.2 행렬의 내적(행렬 곱)

In [6]:
A = np.array([[1,2],[3,4]])
print(A.shape)
B = np.array([[5,6],[7,8]])
print(B.shape)
print(np.dot(A,B)) # 행렬 내적

(2, 2)
(2, 2)
[[19 22]
 [43 50]]


In [8]:
A = np.array([[1,2,3],[4,5,6]])
print(A.shape)
B = np.array([[1,2],[3,4],[5,6]])
print(B.shape)
print(np.dot(A,B))

(2, 3)
(3, 2)
[[22 28]
 [49 64]]


In [10]:
C = np.array([[1,2],[3,4]])
print(C.shape)
print(A.shape)
print(np.dot(A,C)) # A, C는 서로 행렬 내적이 가능한 형태가 아니다. 따라서 ValueError가 난다.

(2, 2)
(2, 3)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [13]:
A = np.array([[1,2],[3,4],[5,6]])
print(A.shape)
B = np.array([7,8])
print(B.shape)
print(np.dot(A,B))

(3, 2)
(2,)
[23 53 83]


## 3.3 신경망의 내적

신경망에서 편향과 활성화 함수를 생략하고 가중치 계산만 생각하면  
가중치 * 입력층을 행렬의 내적으로 나타낼 수 있다.  

In [14]:
X = np.array([1,2]) # 입력층
print(X.shape)
W = np.array([[1,3,5],[2,4,6]]) # 가중치
print(W)
print(W.shape)
Y = np.dot(X,W)
print(Y)

(2,)
[[1 3 5]
 [2 4 6]]
(2, 3)
[ 5 11 17]
